//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestShop.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BestShop.Common.Resources.PropertyDictionary", typeof(PropertyDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمات عبور  یکسان نیست.
        /// </summary>
        public static string ComparePasswordErrorMessage {
            get {
                return ResourceManager.GetString("ComparePasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل تکراری است..
        /// </summary>
        public static string EmailIsDuplicated {
            get {
                return ResourceManager.GetString("EmailIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده معتبر نمی باشد..
        /// </summary>
        public static string GnEmailFormatErrorMessage {
            get {
                return ResourceManager.GetString("GnEmailFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر طول {0} برابر {1} کاراکتر است..
        /// </summary>
        public static string GnMaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("GnMaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل طول {0} برابر {1} کاراکتر است..
        /// </summary>
        public static string GnMinLengthErrorMessage {
            get {
                return ResourceManager.GetString("GnMinLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا {0} را وارد کنید..
        /// </summary>
        public static string GnRequiredErrorMessage {
            get {
                return ResourceManager.GetString("GnRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی رخ داده است لطفا مجددا تلاش کنید.
        /// </summary>
        public static string GnSomethingWenWrong {
            get {
                return ResourceManager.GetString("GnSomethingWenWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد نمیتواند خالی باشد.
        /// </summary>
        public static string PasswordCantBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور باید شامل عدد باشد.
        /// </summary>
        public static string PasswordMustContainDigit {
            get {
                return ResourceManager.GetString("PasswordMustContainDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور باید شامل حداقل 1 حرف کوچک باشد.
        /// </summary>
        public static string PasswordMustContainLowerCase {
            get {
                return ResourceManager.GetString("PasswordMustContainLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور باید شامل کاراکتر های ویژه باشد.
        /// </summary>
        public static string PasswordMustContainSpecialChar {
            get {
                return ResourceManager.GetString("PasswordMustContainSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور باید شامل حداقل 1 حرف بزرگ باشد.
        /// </summary>
        public static string PasswordMustContainUpperCase {
            get {
                return ResourceManager.GetString("PasswordMustContainUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور.
        /// </summary>
        public static string RePassword {
            get {
                return ResourceManager.GetString("RePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتمام ثبت نام.
        /// </summary>
        public static string SuccessRegister {
            get {
                return ResourceManager.GetString("SuccessRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری تکراری است..
        /// </summary>
        public static string UserNameIsDuplicated {
            get {
                return ResourceManager.GetString("UserNameIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید ایمیل.
        /// </summary>
        public static string VerifyEmail {
            get {
                return ResourceManager.GetString("VerifyEmail", resourceCulture);
            }
        }
    }
}
